### ISSUE TITLE
publish event_manager to crates.io

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/event-manager#17]
There are other projects investigating to adopt the event_manager crate, so hope we could publish this crate soon:)

**Comment by andreeaflorescu** [comment]
@jiangliu I created a milestone with what is needed for publishing this to crates.io: https://github.com/rust-vmm/event-manager/milestone/1

I expect to finish this in the next 2 weeks. I'll be needing reviewers :))

**Comment by jiangliu** [comment]
> @jiangliu I created a milestone with what is needed for publishing this to crates.io: https://github.com/rust-vmm/event-manager/milestone/1
> 
> I expect to finish this in the next 2 weeks. I'll be needing reviewers :))

Thanks for help, and I will be glad to review the PRs:)

**Comment by andreeaflorescu** [comment]
Published: https://crates.io/crates/event-manager
