### ISSUE TITLE
Add performance and integration tests for remote-endpoint

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/event-manager#32]

**Comment by alexandruag** [comment]
Right now we see remote endpoint actions as being on the slow path, so we're not adding them to the performance tests (similar to some of the `EventManager` methods such as `add_subscriber`, etc). Opened #35 to address the integration testing part.

**Comment by andreeaflorescu** [comment]
Sounds good.

**Comment by andreeaflorescu** [comment]
Fixed by: #35
