### ISSUE TITLE
race condition causing false event callback

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [rust-vmm/event-manager#41]
I have an fd (say with number 10) in the dispatch queue. before fd 10 dispatched I have dropped fd 10 (also removed via `EventOps::remove`) and create a new eventfd and add it via `EventOps::add`. There is a high chance that new eventfd will receive the same fd number 10 as kernel always assigns a lowest possible number.

In the above scenario, even though my new eventfd has not got any event, my subscriber process callback will be triggered.

quick sample code to reproduce above race condition: [https://gist.github.com/KarthikNedunchezhiyan/39fbdd3eee4b97ab540bf3cb16b21313](https://gist.github.com/KarthikNedunchezhiyan/39fbdd3eee4b97ab540bf3cb16b21313)

above code produces the output like below
```
added fd 4
added fd 5
event received for subscriber uuid 1
removed fd 4
removed fd 5
added fd 4
added fd 5
event received for subscriber uuid 2
```

Even though I have not produced the event to the subscriber uuid 2, It is getting called.

**Comment by alexandruag** [comment]
Hi, thanks for the report! You are right, this is an edge case we should address somehow (and we should also better document potential caveats such as what you're describing, the interaction between `epoll` and `dup`, etc).

**Comment by jiangliu** [comment]
Got your point:)
You are right, it's a race window a little hard to solve.

**Comment by KarthikNedunchezhiyan** [comment]
@jiangliu yes, one simple solution will be to have a buffer to keep track of newly added fds during dispatch phase. Sample code [https://github.com/KarthikNedunchezhiyan/event-manager/commit/027bf45394b98d7a69789b50248b5cb491fb9cbf](https://github.com/KarthikNedunchezhiyan/event-manager/commit/027bf45394b98d7a69789b50248b5cb491fb9cbf)

**Comment by jiangliu** [comment]
Proposed a patch to fix the race condition in another way: https://github.com/rust-vmm/event-manager/pull/43
Seems we should add an test case for the race window first:)

**Comment by jiangliu** [comment]
Seems we could extend utilities::CounterSubscriberWithData() to build unit test cases for the race condition.

**Comment by andreeaflorescu** [comment]
Fixed by: https://github.com/rust-vmm/event-manager/commit/752503bf6d08440ae19a91edfa451ea24001e597
