### ISSUE TITLE
Implement iterator to walk all pending IO events

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/event-manager#44]
With https://github.com/rust-vmm/event-manager/pull/43 merged, it would be better to implement an iterator for pending IO events for better abstraction.

**Comment by smortime** [comment]
I can help out with this.

Should I wait on #45 or branch off it?

**Comment by andreeaflorescu** [comment]
@smortime You don't need to wait on that PR. I don't really have time now for PR #45 so if you want to pick that up as well, I don't mind. You can take the commit from that branch, and add it to your PR (or you can just take the code directly and modify it as you see fit). Lemme know if you need help with anything!

**Comment by smortime** [comment]
Awesome, sounds good. I'll probably nab that commit to start this ticket then. Thanks @andreeaflorescu!

**Comment by jain98** [comment]
Hi, I've been working on this issue for a bit now. I've tried a few different things  after combining changes in [#45](https://github.com/rust-vmm/event-manager/pull/45) but haven't been able to get to a solution that actually works.

After the addition of the ReadyEvents struct the EpollWrapper struct looks as below -
```
/// Collection of events corresponding to the `epoll` ready list.
pub(crate) struct ReadyEvents(Vec<EpollEvent>);
impl ReadyEvents {
    /// Creates a new `ReadyEvents` with `capacity`.
    fn new(capacity: usize) -> Self {
        ReadyEvents(vec![EpollEvent::default(); capacity])
    }

    /// Remove the `EpollEvent` that corresponds to `fd`.
    fn remove(&mut self, fd: RawFd) {
        for event in self.0.iter_mut() {
            if event.fd() == fd {
                *event = EpollEvent::default();
            }
        }
    }
}

impl<'a> IntoIterator for &'a ReadyEvents {
    type Item = EpollEvent;
    type IntoIter = std::vec::IntoIter<EpollEvent>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.clone().into_iter()
    }
}

impl Deref for ReadyEvents {
    type Target = Vec<EpollEvent>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for ReadyEvents {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

// Internal use structure that keeps the epoll related state of an EventManager.
pub(crate) struct EpollWrapper {
    // The epoll wrapper.
    pub(crate) epoll: Epoll,
    // Records the id of the subscriber associated with the given RawFd. The event event_manager
    // does not currently support more than one subscriber being associated with an fd.
    pub(crate) fd_dispatch: HashMap<RawFd, SubscriberId>,
    // Records the set of fds that are associated with the subscriber that has the given id.
    // This is used to keep track of all fds associated with a subscriber.
    pub(crate) subscriber_watch_list: HashMap<SubscriberId, Vec<RawFd>>,
    // A scratch buffer to avoid allocating/freeing memory on each poll iteration.
    pub(crate) ready_events: ReadyEvents,
}
```
The change that I added here is the IntoIterator trait implementation.

The dispatch_event method in manager.rs looks as below -

```
    fn dispatch_events(&mut self, event_count: usize) {
        // EpollEvent doesn't implement Eq or PartialEq, so...
        let default_event: EpollEvent = EpollEvent::default();

        // Used to record whether there's an endpoint event that needs to be handled.
        #[cfg(feature = "remote_endpoint")]
        let mut endpoint_event = None;

        // TODO: implement an iterator for EpollWrapper to simplify the abstraction
        // https://github.com/rust-vmm/event-manager/issues/44
        for event in &self.epoll_context.ready_events {
            // let a = self.epoll_context.ready_events;
            let fd = event.fd();

            // Check whether this event has been discarded.
            // EpollWrapper::remove_event() discards an IO event by setting it to default value.
            if event.events() == default_event.events() && fd == default_event.fd() {
                continue;
            }

            if let Some(subscriber_id) = self.epoll_context.subscriber_id(fd) {
                self.subscribers.get_mut_unchecked(subscriber_id).process(
                    Events::with_inner(event),
                    // The `subscriber_id` is valid because we checked it before.
                    &mut self.epoll_context.ops_unchecked(subscriber_id),
                );
            } else {
                #[cfg(feature = "remote_endpoint")]
                {
                    // If we got here, there's a chance the event was triggered by the remote
                    // endpoint fd. Only check for incoming endpoint events right now, and defer
                    // actually handling them until all subscriber events have been handled first.
                    // This prevents subscribers whose events are about to be handled from being
                    // removed by an endpoint request (or other similar situations).
                    if fd == self.channel.fd() {
                        endpoint_event = Some(event);
                        continue;
                    }
                }

                // This should not occur during normal operation.
                unreachable!("Received event on fd from subscriber that is not registered");
            }
        }

        #[cfg(feature = "remote_endpoint")]
        self.dispatch_endpoint_event(endpoint_event);
    }
```
This code was able to compile but some of the unit tests did not pass. The test_single_threaded test in basic_event_manager.rs was failing because the CounterSubscribers' actual counter values were 2 but expected counter values were 1.

Could someone maybe give me some pointers regarding how I can unblock myself? Based on my understanding we're making a copy of each event in the ready event list in the [existing](https://github.com/rust-vmm/event-manager/blob/master/src/manager.rs#L149) code. My changes are technically doing the same thing. So I'm not completely sure why the tests are failing.

**Comment by andreeaflorescu** [comment]
@jain98 can you add an RFC PR with your code? It is a bit hard otherwise to see what could go wrong.

**Comment by jain98** [comment]
@andreeaflorescu I created a draft pr [here](https://github.com/rust-vmm/event-manager/pull/54). Is this what you were looking for?

**Comment by andreeaflorescu** [comment]
@jain98 yes, thanks. I am a bit booked right now, i'll try to take a look in the following days.

**Comment by jain98** [comment]
Was able to resolve the previously failing test case. Got another unit test failing now. Will take a look at it and update status here.

**Comment by jain98** [comment]
@andreeaflorescu @jiangliu Taking a look at this after a while. After trying numerous things to implement an iterator to walk all pending IO events (represented by a ReadyList, that was created in [#45](https://github.com/rust-vmm/event-manager/pull/45) by @andreeaflorescu, I'm not sure if we can do it. Any non-consuming iterator to walk pending IO events will borrow a reference to self.epoll_context which is already borrowed mutably further in the loop.

I may be missing something or a specific technique to do this, so correct me if I am wrong. I think we may be able to achieve this using interior mutability, but I wonder if it's worth the complexity.

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu @jiangliu Taking a look at this after a while. After trying numerous things to implement an iterator to walk all pending IO events (represented by a ReadyList, that was created in [#45](https://github.com/rust-vmm/event-manager/pull/45) by @andreeaflorescu, I'm not sure if we can do it. Any non-consuming iterator to walk pending IO events will borrow a reference to self.epoll_context which is already borrowed mutably further in the loop.

I tend to agree with you. We're sorry that we've chimed in so late, I can't find a better way of expressing the iterator, and I think we should leave it as is.

@jiangliu do you have a different opinion?

**Comment by jain98** [comment]
> I tend to agree with you. We're sorry that we've chimed in so late, I can't find a better way of expressing the iterator, and I think we should leave it as is.

It's all good. I took a look at this problem multiple times each time arriving at a similar roadblock related to borrowing. Let me know if we decide to close this issue.

**Comment by jiangliu** [comment]
I have given it a try but failed again. Essentially the iterator will hold a reference to the ready_set[], and the callback may change the ready_set[] too. So there's always lifetime conflicts in dispatch_events().

**Comment by jiangliu** [comment]
Mission impossible! We should just remove the comments :
-        // TODO: implement an iterator for EpollWrapper to simplify the abstraction
-        // https://github.com/rust-vmm/event-manager/issues/44

**Comment by jain98** [comment]
I can send a pull request for that. Or one of you can do it, whichever is faster.

**Comment by jiangliu** [comment]
Welcome you to submit PR if convenient:)

**Comment by andreeaflorescu** [comment]
@jain98 sorry again for this. We mislabeled it as a "good first issue", when it definitely was not!

**Comment by jain98** [comment]
Hah, I definitely learned a lot doing this :)

**Comment by andreeaflorescu** [comment]
Closing this, as we did not find a suitable way to implement it.
