### ISSUE TITLE
patch release

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [rust-vmm/event-manager#46]
As 0.1.0 version of this crate has crash possible cases and also solution merged in master, can we make a patch release?

**Comment by alexandruag** [comment]
That makes a lot of sense, we should def do a release soon.

**Comment by andreeaflorescu** [comment]
We need to first resolve #39

**Comment by alexandruag** [comment]
Manually reopening this (looks like merging the PR closed it automatically) until we actually publish the new version. Should we yank the affected ones?

**Comment by alexandruag** [comment]
My bad, looks like it's published already. Should we get rid of 0.1.0?

**Comment by andreeaflorescu** [comment]
Yanked 0.1.0.
